spring:
  datasource:
    # 动态数据源配置，默认数据源
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: true  #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/flowable?nullCatalogMeansCurrent=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
          username: root
          password: root
#          driver-class-name: org.h2.Driver
#          url: jdbc:h2:~/flowable-db;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9093;DB_CLOSE_DELAY=-1
#          username: sa
#          password: 123456
        secondary:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/flowable?nullCatalogMeansCurrent=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
          username: root
          password: root
  security:
    user:
      name: admin
      password: admin
      roles: ACTUALTOR_ADMIN
    filter:
      dispatcher-types: REQUEST,FORWARD,ASYNC
  aop:
    proxy-target-class: true
    auto: true
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  common:
    app:
      idm-admin:
        user: admin
        password: admin
  rest:
    app:
      authentication-mode: verify-privilege
  modeler:
    app:
      rest-enabled: true
  database-schema-update: true
  idm:
    app:
      admin:
        password: admin
        user-id: admin
        first-name: admin
        last-name: cyneck
      rest-enabled: true
    enabled: true
  rest-api-enabled: true



mybatis-plus:
  mapper-locations: classpath*:mappers/*Mapper.xml
  type-aliases-package: com.**.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #mp2.3+ 全局表前缀 mp_
    #table-prefix: mp_
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 4
    logic-not-delete-value: 0
    configuration:
      #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
      map-underscore-to-camel-case: true
      cache-enabled: false
      #配置JdbcTypeForNull, oracle数据库必须配置
      jdbc-type-for-null: 'null'

management:
  endpoints:
    web:
      exposure:
        include: health, info, shutdown
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  health:
    ldap:
      enabled: false

server:
  servlet:
    context-path: /workflow
  port: 8081
swagger:
  enable: true
